version: '3.9'

services:
  web : 
      build: .
      restart: 'always'
      ports : 
        - "8081:8081"
      environment:
        # - SHOPIFY_API_KEY=dbbfc25c030f302ab9503dec45c46c8c
        # - SHOPIFY_API_SECRET=684ea7b602e648198add8a438ed84a3f
        # - SHOP=dev-store-1196.myshopify.com
        # - EMAIL_USERNAME=notifications@leaclothingco.com
        # - EMAIL_PASSWORD=LeaMarketing2022!
        # - EMAIL_HOST=smtpout.secureserver.net
        - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
        - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
        - SHOP=dev-store-1196.myshopify.com
        - EMAIL_USERNAME=${EMAIL_USERNAME}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - EMAIL_HOST=smtpout.secureserver.net